const baeCafeS2 = {
  weapon: {
    weapon_none: 1403,
    'weapon-B-11energygun-greyred': 40,
    weapon_R_420raffle_specialcoloredition: 21,
    'weapon-B-11energygun-greyblue': 40,
    'weapon-K-99raffle-blue': 30,
    'weapon-R-420raffle-grey': 30,
    'weapon-K-99raffle-redgold': 30,
    'weapon-K-99raffle-grey': 30,
    'weapon-R-420raffle-red': 30,
    weapon_A_00pewpew_specialcoloredition: 24,
    'weapon-B-11energygun-red': 40,
    'weapon-C-415-mechpike-alpha': 70,
    'weapon-C-415-mechpike-beta': 70,
    weapon_K_99raffle_specialcoloredition: 22,
    'weapon-B-11energygun-whiteblue': 40,
    'weapon-rocketlauncher-black': 30,
    'weapon-R-420raffle-whiteblue': 30,
    weapon_rocket_launcher_specialcoloredition: 21,
    'weapon-A-00pewpew-red': 36,
    weapon_B_11energygun_specialcoloredition: 26,
    weapon_de_fi_note: 15,
    'weapon-K-99raffle-blackred': 30,
    weapon_AI_commander_sword_specailcoloredition: 21,
    'weapon-rocketlauncher-blue': 30,
    'weapon-R-420raffle-black': 30,
    'weapon-A-00pewpew-blue': 30,
  },
  background: {
    'background-fog-green': 210,
    'background-cybercity-1': 146,
    'background-fog-pink': 210,
    'background-fog-yellow': 163,
    'background-fog-orange': 210,
    background_neoncity_light: 40,
    'background-fog-lightblue': 210,
    'background-cybercity-3': 150,
    'background-fog-grey': 210,
    'background-cybercity-2': 150,
    background_nightcity: 40,
    'background-fog-purple': 210,
    'background-cybercity-4': 150,
    background_neonstreet: 40,
    background_shipcapital: 40,
    background_neoncity_night: 40,
  },
    body: {
      bodytanline: 733,
      bodydark: 743,
      bodymilky: 743,
    },
    skintone: {
      skintonemilky: 1310,
      skintonetanline: 670,
      skintonedark: 239,
    },
    eyebrow: {
      eyebrowhappy: 660,
      eyebrowangry: 440,
      eyebrowconfuse: 259,
      eyebrowsmile: 860,
    },
    mouth: {
      mouthsharkteethopenmouth: 145,
      mouthV: 145,
      mouthrage: 186,
      mouthO: 145,
      mouthnormal: 293,
      mouthsmirk: 188,
      mouthsharkteeth: 130,
      mouthlaugh: 153,
      mouthtongh: 208,
      mouthsmile: 183,
      mouthlolipop: 161,
      mouthuwu: 75,
      mouthmechmaskwhiteblack: 170,
      mouthmechmaskspecialcoloredition: 25,
      mouthsmirksharpteeth: 12,
    },
    cloth: {
      clothcosmosbrownblack: 100,
      clothlightgeararmewhiteblue: 30,
      clothroyalknightwhite: 80,
      clothmechassultarmerwhiteblue: 100,
      clothlightgeararmergrey: 100,
      clothmechassultarmerspecialcoloredition: 24,
      clothlightgeararmerblack: 100,
      clothmecknightredyellow: 30,
      clothroyalknightblack: 100,
      clothbloodwarriersgrey: 100,
      clothbloodwarriersred: 30,
      clothbloodwarrierswhiteblue: 30,
      clothheavarmerwhiteblue: 30,
      clothmedicgearsuitblackblue: 100,
      clothroyalknightspecialcoloredition: 20,
      clothroyalknightred: 30,
      clothbloodwarriersyellow: 30,
      clothmedicgearsuitwhiteblue: 100,
      clothmecknightspecialcoloredition: 26,
      clothdefensivetypespecialcoloredition: 26,
      clothandroidbluewhite: 103,
      clothdefensivetypewhite: 100,
      clothandroidblackred: 36,
      clothlightgeararmerred: 30,
      clothmechassultarmeredgold: 30,
      clothheavarmerspecialcoloredition: 22,
      clothdefensivetypeblack: 100,
      clothmecknightwhite: 100,
      clothandroidblackyellow: 30,
      clothheavarmerblackblue: 70,
      clothheavarmered: 30,
      clothdefensivetypered: 30,
      clothmedicgearsuitred: 30,
      clothmecknightpurple: 30,
      clothcosmoswhite: 30,
      clothmedicgearsuitspecialcoloredition: 26,
      clothlightgeararmerspecialcoloredition: 26,
      clothcosmosredblack: 30,
      clothdefensivetypeblue: 30,
      clothmechassultarmeblackred: 30,
      clothbloodwarrierspecialcoloreditionlight: 15,
      clothheavarmerblackred: 30,
      clothbloodwarrierspecialcoloreditiondark: 15,
      clothmecknightblackred: 30,
      clothcosmosblackwhite: 30,
    },
    eye: {
      eyesshockred: 100,
      eyesshockgreen: 30,
      eyessharpwhite: 129,
      eyesmeanred: 104,
      eyescuteblue: 131,
      eyesshockblue: 110,
      eyeswinkred: 109,
      eyesmeanblack: 100,
      eyessmile: 148,
      eyeswinkpurple: 20,
      eyessharpred: 129,
      eyessharpblack: 120,
      eyesshockyellow: 30,
      eyessharpyellow: 29,
      eyessharpheterochrome: 38,
      eyescutewhite: 127,
      eyescuteyellow: 20,
      eyessharppurple: 24,
      eyeswinkblack: 63,
      eyessharpblue: 35,
      eyeswinkgreen: 20,
      eyescutered: 20,
      eyeswinkblue: 112,
      eyesmeayellow: 25,
      eyesmeanblue: 24,
      eyeswinkwhite: 75,
      eyesclose: 145,
      eyesshockblack: 108,
      eyeswinkyellow: 20,
      eyescuteheterochrome: 30,
      eyessharpgreen: 24,
      eyesmeangreen: 20,
    },
    classlogo: {
      classlogo_shojo: 1353,
      classlogo_phox: 666,
      classlogovalk: 200,
    },
    hairfront: {
      hairfront_curlylonghair_brown: 81,
      hairfront_Ponytail_darkred: 29,
      hairfront_Ponytail_white: 109,
      hairfront_curlytwintail_black: 69,
      hairfront_layerslong_brown: 85,
      hairfront_layerslongwithkitsunemecheartypealpha: 45,
      hairfront_curlylonghair_red: 112,
      hairfront_layersshort_red: 24,
      hairfront_layerslong_white: 117,
      hairfront_curlylonghair_white: 97,
      hairfront_layerslong_blue: 41,
      hairfront_messy_blue: 13,
      hairfront_pigtail_brown: 11,
      hairfront_shortcurlyhairwithmechknighthelmet: 8,
      hairfront_shortcurlyhair_white: 21,
      hairfront_Ponytail_purple: 42,
      hairfront_shortstraighthair_lightblue: 7,
      hairfront_Ponytail_black: 84,
      hairfront_curlylonghair_yellow: 31,
      hairfront_Ponytailwithmechonimask: 53,
      hairfront_shortcurlyhair_brown: 16,
      hairfront_ninjatwintail_white: 28,
      hairfront_pigtail_orange: 8,
      hairfront_ninjatwintail_black: 22,
      hairfront_layersshort_blue: 27,
      hairfront_shortpigtail_white: 23,
      hairfront_curlylonghair_blue: 67,
      hairfront_shortstraighthair_black: 24,
      hairfront_layersshort_grey: 92,
      hairfront_longstraighthair_brown: 77,
      hairfront_curlytwintail_orange: 37,
      hairfront_longstraighthair_lightblue: 35,
      hairfront_messywithkitsunemecheartypebeta: 26,
      hairfront_layersshort_brown: 76,
      hairfront_layersshortwithtwinhorn: 13,
      hairfront_ninjatwintail_red: 17,
      hairfront_longstraighthair_red: 26,
      hairfront_curlytwintail_blue: 47,
      hairfront_shortcurlyhair_pink: 12,
      hairfront_curlylonghairwithbeastmask: 41,
      hairfront_curlytwintail_red: 40,
      hairfront_Ponytail_blue: 41,
      hairfront_shorthair_brown: 34,
      hairfront_messy_brown: 46,
      hairfront_pigtail_white: 29,
      hairfront_curlytwintail_white: 57,
      hairfront_shortstraighthair_brown: 15,
      hairfront_shortponytail_white: 7,
      hairfront_pigtail_darkblue: 7,
      hairfront_layerslong_red: 44,
      hairfront_shortpigtail_yellow: 7,
      hairfront_shortstraighthair_navyblue: 6,
      hairfront_shortponytail_brown: 6,
      hairfront_longstraighthairwithpeakedcap: 8,
      hairfront_shortpigtail_black: 11,
      hairfront_shortponytail_red: 6,
      hairfront_shortpigtail_blue: 3,
      hairfront_ninjatwintail_blue: 18,
      hairfront_shorthairwithdragonhelmet: 6,
      hairfront_shortcurlyhair_lightblue: 6,
      hairfront_messy_red: 8,
      hairfront_shortpigtail_brown: 4,
      hairfront_messy_yellow: 12,
      hairfront_shortponytail_blue: 5,
    },
    hairshadow: {
      hairshadow_curlylonghair: 388,
      hairshadow_Ponytail: 305,
      hairshadow_curlytwintail: 250,
      hairshadow_layerslong: 287,
      hairshadow_layerslongwithkitsunemecheartypealpha: 45,
      hairshadow_layersshort: 219,
      hairshadow_messy: 79,
      hairshadow_pigtail: 55,
      hairshadow_shortcurlyhairwithmechknighthelmet: 8,
      hairshadow_shortcurlyhair: 55,
      hairshadow_shortstraighthair: 52,
      hairshadow_Ponytailwithmechonimask: 53,
      hairshadow_ninjatwintail: 85,
      hairshadow_shortpigtail: 48,
      hairshadow_longstraighthair: 138,
      hairshadow_messywithkitsunemecheartypebeta: 26,
      hairshadow_layersshortwithtwinhorn: 13,
      hairshadow_curlylonghairwithbeastmask: 41,
      hairshadow_shorthair: 34,
      hairshadow_shortponytail: 24,
      hairshadow_longstraighthairwithpeakedcap: 8,
      hairshadow_shorthairwithdragonhelmet: 6,
    },
    hairback: {
      hairback_curlylonghair_brown: 81,
      hairback_Ponytail_darkred: 29,
      hairback_Ponytail_white: 109,
      hairback_curlytwintail_black: 69,
      hairback_layerslong_brown: 85,
      hairback_layerslongwithkitsunemecheartypealpha: 45,
      hairback_curlylonghair_red: 112,
      hairback_layersshort_red: 24,
      hairback_layerslong_white: 117,
      hairback_curlylonghair_white: 97,
      hairback_layerslong_blue: 41,
      hairback_messy_blue: 13,
      hairback_pigtail_brown: 11,
      hairback_shortcurlyhairwithmechknighthelmet: 8,
      hairback_shortcurlyhair_white: 21,
      hairback_Ponytail_purple: 42,
      hairback_shortstraighthair_lightblue: 7,
      hairback_Ponytail_black: 84,
      hairback_curlylonghair_yellow: 31,
      hairback_Ponytailwithmechonimask: 53,
      hairback_shortcurlyhair_brown: 16,
      hairback_ninjatwintail_white: 28,
      hairback_pigtail_orange: 8,
      hairback_ninjatwintail_black: 22,
      hairback_layersshort_blue: 27,
      hairback_shortpigtail_white: 23,
      hairback_curlylonghair_blue: 67,
      hairback_shortstraighthair_black: 24,
      hairback_layersshort_grey: 92,
      hairback_longstraighthair_brown: 77,
      hairback_curlytwintail_orange: 37,
      hairback_longstraighthair_lightblue: 35,
      hairback_messywithkitsunemecheartypebeta: 26,
      hairback_layersshort_brown: 76,
      hairback_layersshortwithtwinhorn: 13,
      hairback_ninjatwintail_red: 17,
      hairback_longstraighthair_red: 26,
      hairback_curlytwintail_blue: 47,
      hairback_shortcurlyhair_pink: 12,
      hairback_curlylonghairwithbeastmask: 41,
      hairback_curlytwintail_red: 40,
      hairback_Ponytail_blue: 41,
      hairback_shorthair_brown: 34,
      hairback_messy_brown: 46,
      hairback_pigtail_white: 29,
      hairback_curlytwintail_white: 57,
      hairback_shortstraighthair_brown: 15,
      hairback_shortponytail_white: 7,
      hairback_pigtail_darkblue: 7,
      hairback_layerslong_red: 44,
      hairback_shortpigtail_yellow: 7,
      hairback_shortstraighthair_navyblue: 6,
      hairback_shortponytail_brown: 6,
      hairback_longstraighthairwithpeakedcap: 8,
      hairback_shortpigtail_black: 11,
      hairback_shortponytail_red: 6,
      hairback_shortpigtail_blue: 3,
      hairback_ninjatwintail_blue: 18,
      hairback_shorthairwithdragonhelmet: 6,
      hairback_shortcurlyhair_lightblue: 6,
      hairback_messy_red: 8,
      hairback_shortpigtail_brown: 4,
      hairback_messy_yellow: 12,
      hairback_shortponytail_blue: 5,
    },
};

const baeKey = [
  'weapon',
  'background',
  'body',
  'skintone',
  'eyebrow',
  'mouth',
  'cloth',
  'eye',
  'classlogo',
  'hairfront',
  'hairshadow',
  'hairback',
];

const language = {
  weapon: 'Weapon',
  weapon_none: 'Weapon none',
  'weapon-B-11energygun-greyred': 'B-11 energy gun greyred',
  weapon_R_420raffle_specialcoloredition: 'R-420 Raffle special color edition',
  'weapon-B-11energygun-greyblue': 'B-11 energy gun greyblue',
  'weapon-K-99raffle-blue': 'K-99 raffle blue',
  'weapon-R-420raffle-grey': 'R-420 Raffle grey',
  'weapon-K-99raffle-redgold': 'K-99 raffle redgold',
  'weapon-K-99raffle-grey': 'K-99 raffle grey',
  'weapon-R-420raffle-red': 'R-420 Raffle red',
  weapon_A_00pewpew_specialcoloredition: 'A-00 pewpew special color edition',
  'weapon-B-11energygun-red': 'B-11 energy gun greyred',
  'weapon-C-415-mechpike-alpha': 'C-415 mechpike-alpha alpha',
  'weapon-C-415-mechpike-beta': 'C-415 mechpike-alpha beta',
  weapon_K_99raffle_specialcoloredition: 'K-99 raffle special color edition',
  'weapon-B-11energygun-whiteblue': 'B-11 energy gun whiteblue',
  'weapon-rocketlauncher-black': 'Rocket launcher black',
  'weapon-R-420raffle-whiteblue': 'R-420 Raffle whiteblue',
  weapon_rocket_launcher_specialcoloredition:
    'Rocket launcher special color edition',
  'weapon-A-00pewpew-red': 'A-00 pewpew red',
  weapon_B_11energygun_specialcoloredition:
    'B-11 energy gun special color edition',
  weapon_de_fi_note: 'Defi note special color edition',
  'weapon-K-99raffle-blackred': 'K-99 raffle blackred',
  weapon_AI_commander_sword_specailcoloredition:
    'Ai commander sword special color edition',
  'weapon-rocketlauncher-blue': 'Rocket launcher blue',
  'weapon-R-420raffle-black': 'R-420 Raffle black',
  'weapon-A-00pewpew-blue': 'A-00 pewpew blue',
  background: 'Background',
  'background-fog-green': 'Fog green',
  'background-cybercity-1': 'Cybercity-1',
  'background-fog-pink': 'Fog pink',
  'background-fog-yellow': 'Fog yellow',
  'background-fog-orange': 'Fog orange',
  background_neoncity_light: 'Neon city light',
  'background-fog-lightblue': 'Fog lightblue',
  'background-cybercity-3': 'Cybercity-3',
  'background-fog-grey': 'Fog grey',
  'background-cybercity-2': 'Cybercity-2',
  background_nightcity: 'Night city',
  'background-fog-purple': 'Fog purple',
  'background-cybercity-4': 'Cybercity-4',
  background_neonstreet: 'Neon street',
  background_shipcapital: 'Ship capital',
  background_neoncity_night: 'Neon city night',
  body: 'Body',
  bodytanline: 'Tanline',
  bodydark: 'Dark',
  bodymilky: 'Milky',
  skintone: 'Skintone',
  skintonemilky: 'Milky',
  skintonetanline: 'Tanline',
  skintonedark: 'Dark',
  eyebrow: 'Eyebrow',
    eyebrowhappy: 'Happy',
    eyebrowangry: 'Angry',
    eyebrowconfuse: 'Confuse',
    eyebrowsmile: 'Smile',
    mouth: 'Mouth',
    mouthsharkteethopenmouth: 'Shark teeth-open mouth',
    mouthV: 'V',
    mouthrage: 'Rage',
    mouthO: 'O',
    mouthnormal: 'Normal',
    mouthsmirk: 'Smirk',
    mouthsharkteeth: 'Shark teeth',
    mouthlaugh: 'laugh',
    mouthtongh: 'Tongh',
    mouthsmile: 'Smile',
    mouthlolipop: 'Lolipop',
    mouthuwu: 'Uwu',
    mouthmechmaskwhiteblack: 'Mechmask white black',
    mouthmechmaskspecialcoloredition: 'Mech mask special color edition',
    mouthsmirksharpteeth: 'Smirk sharp teeth',
    cloth: 'Cloth',
    clothcosmosbrownblack: 'Cosmos brownblack',
    clothlightgeararmewhiteblue: 'Light gear armer white blue',
    clothroyalknightwhite: 'Royal knight white',
    clothmechassultarmerwhiteblue: 'Mech assult armer whiteblue',
    clothlightgeararmergrey: 'Light gear armer grey',
    clothmechassultarmerspecialcoloredition: 'Mech assult armer special color edition',
    clothlightgeararmerblack: 'Light gear armer black',
    clothmecknightredyellow: 'Mech knight redyellow',
    clothroyalknightblack: 'Royal knight black',
    clothbloodwarriersgrey: 'Blood warriers grey',
    clothbloodwarriersred: 'Blood warriers red',
    clothbloodwarrierswhiteblue: 'Blood warriers white blue',
    clothheavarmerwhiteblue: 'Heavy armer whiteblue',
    clothmedicgearsuitblackblue: 'Medic gear suit blackblue',
    clothroyalknightspecialcoloredition: 'Royal knight special color edition',
    clothroyalknightred: 'Royal knight red',
    clothbloodwarriersyellow: 'Blood warriers yellow',
    clothmedicgearsuitwhiteblue: 'Medic gear suit whiteblue',
    clothmecknightspecialcoloredition: 'Mech knight special color edition',
    clothdefensivetypespecialcoloredition: 'Defensive type special color edition',
    clothandroidbluewhite: 'Android bluewhite',
    clothdefensivetypewhite: 'Defensive type white',
    clothandroidblackred: 'Android blackred',
    clothlightgeararmerred: 'Light gear armer red',
    clothmechassultarmeredgold: 'Mech assult armer red gold',
    clothheavarmerspecialcoloredition: 'Heavy armer special color edition',
    clothdefensivetypeblack: 'Defensive type black',
    clothmecknightwhite: 'Mech knight white',
    clothandroidblackyellow: 'Android blackyellow',
    clothheavarmerblackblue: 'Heavy armer blackblue',
    clothheavarmered: 'Heavy armer red',
    clothdefensivetypered: 'Defensive type red',
    clothmedicgearsuitred: 'Medic gear suit red',
    clothmecknightpurple: 'Mech knight purple',
    clothcosmoswhite: 'Cosmos white',
    clothmedicgearsuitspecialcoloredition: 'Medic gear suit special color edition',
    clothlightgeararmerspecialcoloredition: 'Light gear armer special color edition',
    clothcosmosredblack: 'Cosmos redblack',
    clothdefensivetypeblue: 'Defensive type blue',
    clothmechassultarmeblackred: 'Mech assult armer black red',
    clothbloodwarrierspecialcoloreditionlight: 'Blood warrier special color edition-light',
    clothheavarmerblackred: 'Heavy armer blackred',
    clothbloodwarrierspecialcoloreditiondark: 'Blood warrier special color edition-dark',
    clothmecknightblackred: 'Mech knight blackred',
    clothcosmosblackwhite: 'Cosmos blackwhite',
    eye: 'Eye',
    eyesshockred: 'Shock red',
    eyesshockgreen: 'Shock green',
    eyessharpwhite: 'Sharp white',
    eyesmeanred: 'Mean red',
    eyescuteblue: 'Cute blue',
    eyesshockblue: 'Shock blue',
    eyeswinkred: 'Wink red',
    eyesmeanblack: 'Mean black',
    eyessmile: 'Smile',
    eyeswinkpurple: 'Wink purple',
    eyessharpred: 'Sharp red',
    eyessharpblack: 'Sharp black',
    eyesshockyellow: 'Shock yellow',
    eyessharpyellow: 'Sharp yellow',
    eyessharpheterochrome: 'Sharp heterochrome',
    eyescutewhite: 'Cute white',
    eyescuteyellow: 'Cute yellow',
    eyessharppurple: 'Sharp purple',
    eyeswinkblack: 'Wink black',
    eyessharpblue: 'Sharp blue',
    eyeswinkgreen: 'Wink green',
    eyescutered: 'Cute red',
    eyeswinkblue: 'Wink blue',
    eyesmeayellow: 'Mean yellow',
    eyesmeanblue: 'Mean blue',
    eyeswinkwhite: 'Wink white',
    eyesclose: 'Close',
    eyesshockblack: 'Shock black',
    eyeswinkyellow: 'Wink yellow',
    eyescuteheterochrome: 'Cute heterochrome',
    eyessharpgreen: 'Sharp green',
    eyesmeangreen: 'Mean green',
    class: 'Class',
    classlogo_shojo: 'Shojo',
    classlogo_phox: 'Phox',
    classlogovalk: 'Valk',
    hairfront: 'Hairfront',
    hairfront_curlylonghair_brown: 'Curly long hair brown',
    hairfront_Ponytail_darkred: 'Pony tail darkred',
    hairfront_Ponytail_white: 'Pony tail white',
    hairfront_curlytwintail_black: 'Curly twin tail black',
    hairfront_layerslong_brown: 'Layers long brown',
    hairfront_layerslongwithkitsunemecheartypealpha: 'Layers long + kitsune mech ear type alpha',
    hairfront_curlylonghair_red: 'Curly long hair red',
    hairfront_layersshort_red: 'Layers short red',
    hairfront_layerslong_white: 'Layers long white',
    hairfront_curlylonghair_white: 'Curly long hair white',
    hairfront_layerslong_blue: 'Layers long blue',
    hairfront_messy_blue: 'Messy blue',
    hairfront_pigtail_brown: 'Pig tail brown',
    hairfront_shortcurlyhairwithmechknighthelmet: 'Short curly hair + mech knight helmet',
    hairfront_shortcurlyhair_white: 'Short curly hair white',
    hairfront_Ponytail_purple: 'Pony tail purple',
    hairfront_shortstraighthair_lightblue: 7,
    hairfront_Ponytail_black: 'Pony tail black',
    hairfront_curlylonghair_yellow: 'Curly long hair yellow',
    hairfront_Ponytailwithmechonimask: 'Pony tail + mech oni mask',
    hairfront_shortcurlyhair_brown: 'Short curly hair brown',
    hairfront_ninjatwintail_white: 'Ninja twin tail white',
    hairfront_pigtail_orange: 'Pig tail orange',
    hairfront_ninjatwintail_black: 'Ninja twin tail black',
    hairfront_layersshort_blue: 'Layers short blue',
    hairfront_shortpigtail_white: 'Short pig tail white',
    hairfront_curlylonghair_blue: 'Curly long hair blue',
    hairfront_shortstraighthair_black: 'Short straight hair black',
    hairfront_layersshort_grey: 'Layers short grey',
    hairfront_longstraighthair_brown: 'Long straight hair brown',
    hairfront_curlytwintail_orange: 'Curly twin tail orange',
    hairfront_longstraighthair_lightblue: 'Long straight hair lightblue',
    hairfront_messywithkitsunemecheartypebeta: 'Messy + kitsune mech ear type beta',
    hairfront_layersshort_brown: 'Layers short brown',
    hairfront_layersshortwithtwinhorn: 'Layers short + twin horn',
    hairfront_ninjatwintail_red: 'Ninja twin tail red',
    hairfront_longstraighthair_red: 'Long straight hair red',
    hairfront_curlytwintail_blue: 'Curly twin tail blue',
    hairfront_shortcurlyhair_pink: 'Short curly hair pink',
    hairfront_curlylonghairwithbeastmask: 'Curly long hair + beast mask',
    hairfront_curlytwintail_red: 'Curly twin tail red',
    hairfront_Ponytail_blue: 'Pony tail blue',
    hairfront_shorthair_brown: 'Short hair brown',
    hairfront_messy_brown: 'Messy brown',
    hairfront_pigtail_white: 'Pig tail white',
    hairfront_curlytwintail_white: 'Curly twin tail white',
    hairfront_shortstraighthair_brown: 'Short straight hair brown',
    hairfront_shortponytail_white: 'Short pony tail white',
    hairfront_pigtail_darkblue: 'Pig tail darkblue',
    hairfront_layerslong_red: 'Layers long red',
    hairfront_shortpigtail_yellow: 'Short pig tail yellow',
    hairfront_shortstraighthair_navyblue: 'Short straight hair navyblue',
    hairfront_shortponytail_brown: 'Short pony tail brown',
    hairfront_longstraighthairwithpeakedcap: 'Long straight hair + peaked cap',
    hairfront_shortpigtail_black: 'Short pig tail black',
    hairfront_shortponytail_red: 'Short pony tail red',
    hairfront_shortpigtail_blue: 'Short pig tail blue',
    hairfront_ninjatwintail_blue: 'Ninja twin tail blue',
    hairfront_shorthairwithdragonhelmet: 'Short hair + dragonhelmet',
    hairfront_shortcurlyhair_lightblue: 'Short curly hair lightblue',
    hairfront_messy_red: 'Messy red',
    hairfront_shortpigtail_brown: 'Short pig tail brown',
    hairfront_messy_yellow: 'Messy yellow',
    hairfront_shortponytail_blue: 'Short pony tail blue',
    hairshadow: 'Hair shadow',
    hairshadow_curlylonghair: 'Curly long hair',
    hairshadow_Ponytail: 'Pony tail',
    hairshadow_curlytwintail: 'Curly twin tail',
    hairshadow_layerslong: 'Layers long',
    hairshadow_layerslongwithkitsunemecheartypealpha: 'Layers long + kitsune mech ear type alpha',
    hairshadow_layersshort: 'Layers short',
    hairshadow_messy: 'Messy',
    hairshadow_pigtail: 'Pig tail',
    hairshadow_shortcurlyhairwithmechknighthelmet: 'Short curly hair + mech knight helmet',
    hairshadow_shortcurlyhair: 'Short curly hair',
    hairshadow_shortstraighthair: 'Short straight hair',
    hairshadow_Ponytailwithmechonimask: 'Pony tail + mech oni mask',
    hairshadow_ninjatwintail: 'Ninja twin tail',
    hairshadow_shortpigtail: 'Short pig tail',
    hairshadow_longstraighthair: 'Long straight hair',
    hairshadow_messywithkitsunemecheartypebeta: 'Messy + kitsune mech ear type beta',
    hairshadow_layersshortwithtwinhorn: 'Layers short + twin horn',
    hairshadow_curlylonghairwithbeastmask: 'Curly long hair + beast mask',
    hairshadow_shorthair: 'Short hair',
    hairshadow_shortponytail: 'Short pony tail',
    hairshadow_longstraighthairwithpeakedcap: 'Long straight hair + peaked cap',
    hairshadow_shorthairwithdragonhelmet: 'Short hair + dragonhelmet',
    hairback: 'Hair back',
    hairback_curlylonghair_brown: 'Curly long hair brown',
    hairback_Ponytail_darkred: 'Pony tail darkred',
    hairback_Ponytail_white: 'Pony tail white',
    hairback_curlytwintail_black: 'Curly twin tail black',
    hairback_layerslong_brown: 'Layers long brown',
    hairback_layerslongwithkitsunemecheartypealpha: 'Layers long + kitsune mech ear type alpha',
    hairback_curlylonghair_red: 'Curly long hair red',
    hairback_layersshort_red: 'Layers short red',
    hairback_layerslong_white: 'Layers long white',
    hairback_curlylonghair_white: 'Curly long hair white',
    hairback_layerslong_blue: 'Layers long blue',
    hairback_messy_blue: 'Messy blue',
    hairback_pigtail_brown: 'Pig tail brown',
    hairback_shortcurlyhairwithmechknighthelmet: 'Short curly hair + mech knight helmet',
    hairback_shortcurlyhair_white: 'Short curly hair white',
    hairback_Ponytail_purple: 'Pony tail purple',
    hairback_shortstraighthair_lightblue: 'Short straight hair lightblue',
    hairback_Ponytail_black: 'Pony tail black',
    hairback_curlylonghair_yellow: 'Curly long hair yellow',
    hairback_Ponytailwithmechonimask: 'Pony tail + mech oni mask',
    hairback_shortcurlyhair_brown: 'Short curly hair brown',
    hairback_ninjatwintail_white: 'Ninja twin tail white',
    hairback_pigtail_orange: 'Pig tail orange',
    hairback_ninjatwintail_black: 'Ninja twin tail black',
    hairback_layersshort_blue: 'Layers short blue',
    hairback_shortpigtail_white: 'Short pig tail white',
    hairback_curlylonghair_blue: 'Curly long hair blue',
    hairback_shortstraighthair_black: 'Short straight hair black',
    hairback_layersshort_grey: 'Layers short grey',
    hairback_longstraighthair_brown: 'Long straight hair brown',
    hairback_curlytwintail_orange: 'Curly twin tail orange',
    hairback_longstraighthair_lightblue: 'Long straight hair lightblue',
    hairback_messywithkitsunemecheartypebeta: 'Messy + kitsune mech ear type beta',
    hairback_layersshort_brown: 'Layer short brown',
    hairback_layersshortwithtwinhorn: 'Layer short with twin horn',
    hairback_ninjatwintail_red: 'Ninja twin tail red',
    hairback_longstraighthair_red: 'Long straight hair red',
    hairback_curlytwintail_blue: 'Curly twin tail blue',
    hairback_shortcurlyhair_pink: 'Short curly hair pink',
    hairback_curlylonghairwithbeastmask: 'Curly long hair + beast mask',
    hairback_curlytwintail_red: 'Curly twin tail red',
    hairback_Ponytail_blue: 'Pony tail blue',
    hairback_shorthair_brown: 'Short hair brown',
    hairback_messy_brown: 'Messy brown',
    hairback_pigtail_white: 'Pig tail white',
    hairback_curlytwintail_white: 'Curly twin tail white',
    hairback_shortstraighthair_brown: 'Short straight hair brown',
    hairback_shortponytail_white: 'Short pony tail white',
    hairback_pigtail_darkblue: 'Pig tail darkblue',
    hairback_layerslong_red: 'Layers long red',
    hairback_shortpigtail_yellow: 'Short pig tail yellow',
    hairback_shortstraighthair_navyblue: 'Short straight hair navyblue',
    hairback_shortponytail_brown: 'Short pony tail brown',
    hairback_longstraighthairwithpeakedcap: 'Long straight hair + peaked cap',
    hairback_shortpigtail_black: 'Short pig tail black',
    hairback_shortponytail_red: 'Short pony tail red',
    hairback_shortpigtail_blue: 'Short pig tail blue',
    hairback_ninjatwintail_blue: 'Ninja twin tail blue',
    hairback_shorthairwithdragonhelmet: 'Short hair + dragonhelmet',
    hairback_shortcurlyhair_lightblue: 'Short curly hair lightblue',
    hairback_messy_red: 'Messy red',
    hairback_shortpigtail_brown: 'Short pig tail brown',
    hairback_messy_yellow: 'Messy yellow',
    hairback_shortponytail_blue: 'Short pony tail blue',
};

export { baeCafeS2, language, baeKey };
